/**
 * WCAG 2.1 success criteria → official W3C Understanding page URLs.
 * Used in the IssueDetailDrawer WCAG References section.
 */
export const WCAG_REFERENCES = {
  '1.1.1': { title: 'Non-text Content', url: 'https://www.w3.org/WAI/WCAG21/Understanding/non-text-content' },
  '1.2.1': { title: 'Audio-only and Video-only (Prerecorded)', url: 'https://www.w3.org/WAI/WCAG21/Understanding/audio-only-and-video-only-prerecorded' },
  '1.2.2': { title: 'Captions (Prerecorded)', url: 'https://www.w3.org/WAI/WCAG21/Understanding/captions-prerecorded' },
  '1.2.3': { title: 'Audio Description or Media Alternative (Prerecorded)', url: 'https://www.w3.org/WAI/WCAG21/Understanding/audio-description-or-media-alternative-prerecorded' },
  '1.2.4': { title: 'Captions (Live)', url: 'https://www.w3.org/WAI/WCAG21/Understanding/captions-live' },
  '1.2.5': { title: 'Audio Description (Prerecorded)', url: 'https://www.w3.org/WAI/WCAG21/Understanding/audio-description-prerecorded' },
  '1.2.6': { title: 'Sign Language (Prerecorded)', url: 'https://www.w3.org/WAI/WCAG21/Understanding/sign-language-prerecorded' },
  '1.2.7': { title: 'Extended Audio Description (Prerecorded)', url: 'https://www.w3.org/WAI/WCAG21/Understanding/extended-audio-description-prerecorded' },
  '1.2.8': { title: 'Media Alternative (Prerecorded)', url: 'https://www.w3.org/WAI/WCAG21/Understanding/media-alternative-prerecorded' },
  '1.2.9': { title: 'Audio-only (Live)', url: 'https://www.w3.org/WAI/WCAG21/Understanding/audio-only-live' },
  '1.3.1': { title: 'Info and Relationships', url: 'https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships' },
  '1.3.2': { title: 'Meaningful Sequence', url: 'https://www.w3.org/WAI/WCAG21/Understanding/meaningful-sequence' },
  '1.3.3': { title: 'Sensory Characteristics', url: 'https://www.w3.org/WAI/WCAG21/Understanding/sensory-characteristics' },
  '1.3.4': { title: 'Orientation', url: 'https://www.w3.org/WAI/WCAG21/Understanding/orientation' },
  '1.3.5': { title: 'Identify Input Purpose', url: 'https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose' },
  '1.3.6': { title: 'Identify Purpose', url: 'https://www.w3.org/WAI/WCAG21/Understanding/identify-purpose' },
  '1.4.1': { title: 'Use of Color', url: 'https://www.w3.org/WAI/WCAG21/Understanding/use-of-color' },
  '1.4.2': { title: 'Audio Control', url: 'https://www.w3.org/WAI/WCAG21/Understanding/audio-control' },
  '1.4.3': { title: 'Contrast (Minimum)', url: 'https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum' },
  '1.4.4': { title: 'Resize Text', url: 'https://www.w3.org/WAI/WCAG21/Understanding/resize-text' },
  '1.4.5': { title: 'Images of Text', url: 'https://www.w3.org/WAI/WCAG21/Understanding/images-of-text' },
  '1.4.6': { title: 'Contrast (Enhanced)', url: 'https://www.w3.org/WAI/WCAG21/Understanding/contrast-enhanced' },
  '1.4.7': { title: 'Low or No Background Audio', url: 'https://www.w3.org/WAI/WCAG21/Understanding/low-or-no-background-audio' },
  '1.4.8': { title: 'Visual Presentation', url: 'https://www.w3.org/WAI/WCAG21/Understanding/visual-presentation' },
  '1.4.9': { title: 'Images of Text (No Exception)', url: 'https://www.w3.org/WAI/WCAG21/Understanding/images-of-text-no-exception' },
  '1.4.10': { title: 'Reflow', url: 'https://www.w3.org/WAI/WCAG21/Understanding/reflow' },
  '1.4.11': { title: 'Non-text Contrast', url: 'https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast' },
  '1.4.12': { title: 'Text Spacing', url: 'https://www.w3.org/WAI/WCAG21/Understanding/text-spacing' },
  '1.4.13': { title: 'Content on Hover or Focus', url: 'https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus' },
  '2.1.1': { title: 'Keyboard', url: 'https://www.w3.org/WAI/WCAG21/Understanding/keyboard' },
  '2.1.2': { title: 'No Keyboard Trap', url: 'https://www.w3.org/WAI/WCAG21/Understanding/no-keyboard-trap' },
  '2.1.3': { title: 'Keyboard (No Exception)', url: 'https://www.w3.org/WAI/WCAG21/Understanding/keyboard-no-exception' },
  '2.1.4': { title: 'Character Key Shortcuts', url: 'https://www.w3.org/WAI/WCAG21/Understanding/character-key-shortcuts' },
  '2.2.1': { title: 'Timing Adjustable', url: 'https://www.w3.org/WAI/WCAG21/Understanding/timing-adjustable' },
  '2.2.2': { title: 'Pause, Stop, Hide', url: 'https://www.w3.org/WAI/WCAG21/Understanding/pause-stop-hide' },
  '2.2.3': { title: 'No Timing', url: 'https://www.w3.org/WAI/WCAG21/Understanding/no-timing' },
  '2.2.4': { title: 'Interruptions', url: 'https://www.w3.org/WAI/WCAG21/Understanding/interruptions' },
  '2.2.5': { title: 'Re-authenticating', url: 'https://www.w3.org/WAI/WCAG21/Understanding/re-authenticating' },
  '2.2.6': { title: 'Timeouts', url: 'https://www.w3.org/WAI/WCAG21/Understanding/timeouts' },
  '2.3.1': { title: 'Three Flashes or Below Threshold', url: 'https://www.w3.org/WAI/WCAG21/Understanding/three-flashes-or-below-threshold' },
  '2.3.2': { title: 'Three Flashes', url: 'https://www.w3.org/WAI/WCAG21/Understanding/three-flashes' },
  '2.3.3': { title: 'Animation from Interactions', url: 'https://www.w3.org/WAI/WCAG21/Understanding/animation-from-interactions' },
  '2.4.1': { title: 'Bypass Blocks', url: 'https://www.w3.org/WAI/WCAG21/Understanding/bypass-blocks' },
  '2.4.2': { title: 'Page Titled', url: 'https://www.w3.org/WAI/WCAG21/Understanding/page-titled' },
  '2.4.3': { title: 'Focus Order', url: 'https://www.w3.org/WAI/WCAG21/Understanding/focus-order' },
  '2.4.4': { title: 'Link Purpose (In Context)', url: 'https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context' },
  '2.4.5': { title: 'Multiple Ways', url: 'https://www.w3.org/WAI/WCAG21/Understanding/multiple-ways' },
  '2.4.6': { title: 'Headings and Labels', url: 'https://www.w3.org/WAI/WCAG21/Understanding/headings-and-labels' },
  '2.4.7': { title: 'Focus Visible', url: 'https://www.w3.org/WAI/WCAG21/Understanding/focus-visible' },
  '2.4.8': { title: 'Location', url: 'https://www.w3.org/WAI/WCAG21/Understanding/location' },
  '2.4.9': { title: 'Link Purpose (Link Only)', url: 'https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-link-only' },
  '2.4.10': { title: 'Section Headings', url: 'https://www.w3.org/WAI/WCAG21/Understanding/section-headings' },
  '2.4.11': { title: 'Focus Not Obscured (Minimum)', url: 'https://www.w3.org/WAI/WCAG21/Understanding/focus-not-obscured-minimum' },
  '2.4.12': { title: 'Focus Not Obscured (Enhanced)', url: 'https://www.w3.org/WAI/WCAG21/Understanding/focus-not-obscured-enhanced' },
  '2.4.13': { title: 'Focus Appearance', url: 'https://www.w3.org/WAI/WCAG21/Understanding/focus-appearance' },
  '2.5.1': { title: 'Pointer Gestures', url: 'https://www.w3.org/WAI/WCAG21/Understanding/pointer-gestures' },
  '2.5.2': { title: 'Pointer Cancellation', url: 'https://www.w3.org/WAI/WCAG21/Understanding/pointer-cancellation' },
  '2.5.3': { title: 'Label in Name', url: 'https://www.w3.org/WAI/WCAG21/Understanding/label-in-name' },
  '2.5.4': { title: 'Motion Actuation', url: 'https://www.w3.org/WAI/WCAG21/Understanding/motion-actuation' },
  '2.5.5': { title: 'Target Size', url: 'https://www.w3.org/WAI/WCAG21/Understanding/target-size' },
  '2.5.6': { title: 'Concurrent Input Mechanisms', url: 'https://www.w3.org/WAI/WCAG21/Understanding/concurrent-input-mechanisms' },
  '2.5.7': { title: 'Dragging Movements', url: 'https://www.w3.org/WAI/WCAG21/Understanding/dragging-movements' },
  '2.5.8': { title: 'Target Size (Minimum)', url: 'https://www.w3.org/WAI/WCAG21/Understanding/target-size-minimum' },
  '3.1.1': { title: 'Language of Page', url: 'https://www.w3.org/WAI/WCAG21/Understanding/language-of-page' },
  '3.1.2': { title: 'Language of Parts', url: 'https://www.w3.org/WAI/WCAG21/Understanding/language-of-parts' },
  '3.1.3': { title: 'Unusual Words', url: 'https://www.w3.org/WAI/WCAG21/Understanding/unusual-words' },
  '3.1.4': { title: 'Abbreviations', url: 'https://www.w3.org/WAI/WCAG21/Understanding/abbreviations' },
  '3.1.5': { title: 'Reading Level', url: 'https://www.w3.org/WAI/WCAG21/Understanding/reading-level' },
  '3.1.6': { title: 'Pronunciation', url: 'https://www.w3.org/WAI/WCAG21/Understanding/pronunciation' },
  '3.2.1': { title: 'On Focus', url: 'https://www.w3.org/WAI/WCAG21/Understanding/on-focus' },
  '3.2.2': { title: 'On Input', url: 'https://www.w3.org/WAI/WCAG21/Understanding/on-input' },
  '3.2.3': { title: 'Consistent Navigation', url: 'https://www.w3.org/WAI/WCAG21/Understanding/consistent-navigation' },
  '3.2.4': { title: 'Consistent Identification', url: 'https://www.w3.org/WAI/WCAG21/Understanding/consistent-identification' },
  '3.2.5': { title: 'Change on Request', url: 'https://www.w3.org/WAI/WCAG21/Understanding/change-on-request' },
  '3.2.6': { title: 'Consistent Help', url: 'https://www.w3.org/WAI/WCAG21/Understanding/consistent-help' },
  '3.3.1': { title: 'Error Identification', url: 'https://www.w3.org/WAI/WCAG21/Understanding/error-identification' },
  '3.3.2': { title: 'Labels or Instructions', url: 'https://www.w3.org/WAI/WCAG21/Understanding/labels-or-instructions' },
  '3.3.3': { title: 'Error Suggestion', url: 'https://www.w3.org/WAI/WCAG21/Understanding/error-suggestion' },
  '3.3.4': { title: 'Error Prevention (Legal, Financial, Data)', url: 'https://www.w3.org/WAI/WCAG21/Understanding/error-prevention-legal-financial-data' },
  '3.3.5': { title: 'Help', url: 'https://www.w3.org/WAI/WCAG21/Understanding/help' },
  '3.3.6': { title: 'Error Prevention (All)', url: 'https://www.w3.org/WAI/WCAG21/Understanding/error-prevention-all' },
  '3.3.7': { title: 'Redundant Entry', url: 'https://www.w3.org/WAI/WCAG21/Understanding/redundant-entry' },
  '3.3.8': { title: 'Accessible Authentication (Minimum)', url: 'https://www.w3.org/WAI/WCAG21/Understanding/accessible-authentication-minimum' },
  '3.3.9': { title: 'Accessible Authentication (Enhanced)', url: 'https://www.w3.org/WAI/WCAG21/Understanding/accessible-authentication-enhanced' },
  '4.1.1': { title: 'Parsing', url: 'https://www.w3.org/WAI/WCAG21/Understanding/parsing' },
  '4.1.2': { title: 'Name, Role, Value', url: 'https://www.w3.org/WAI/WCAG21/Understanding/name-role-value' },
  '4.1.3': { title: 'Status Messages', url: 'https://www.w3.org/WAI/WCAG21/Understanding/status-messages' },
}
